title: Roep een functie aan gebaseerd op de waarde van de potentiometer (instelwiel)
hero_image: images/banner.png
description: Roep een functie aan gebaseerd op de waarde van de potentiometer (instelwiel)
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Roep een functie aan gebaseerd op de waarde van de potentiometer (instelwiel)
