title: Call a function based on the value of the potentiometer
hero_image: images/banner.png
description: Call a function based on the value of the potentiometer
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Call a function based on the value of the potentiometer
